const API_BASE_URL_DEV = 'https://fluxoapi.azurewebsites.net/api';
const API_BASE_URL_PROD = 'https://fluxoapi.azurewebsites.net/api';

const ENDPOINTS = {
    GET_TODOS: '/estabelecimentosapi/todos',
    GET_POR_ID: '/estabelecimentosapi/{id}',
    POST_CRIAR: '/estabelecimentosapi/criar',
    POST_ATUALIZAR: '/estabelecimentosapi/atualizar',
    POST_DELETAR: '/estabelecimentosapi/deletar',
    GET_POR_TIPO_CATEGORIAID_MAIS_SIGLA_ESTADO_USUARIO: '/estabelecimentosapi/getPorEstabelecimentoTipoIdMaisCidadeIdUsuarioLogado',
    GET_POR_QUERY: '/estabelecimentosapi/getPorQuery'
};

const DEV = {
    API_URL_GET_TODOS: `${API_BASE_URL_DEV}/${ENDPOINTS.GET_TODOS}`,
    API_URL_GET_POR_ID: `${API_BASE_URL_DEV}/${ENDPOINTS.GET_POR_ID}`,
    API_URL_POST_CRIAR: `${API_BASE_URL_DEV}/${ENDPOINTS.POST_CRIAR}`,
    API_URL_POST_ATUALIZAR: `${API_BASE_URL_DEV}/${ENDPOINTS.POST_ATUALIZAR}`,
    API_URL_POST_DELETAR: `${API_BASE_URL_DEV}/${ENDPOINTS.POST_DELETAR}`,
    API_URL_GET_POR_TIPO_CATEGORIAID_MAIS_SIGLA_ESTADO_USUARIO: `${API_BASE_URL_DEV}/${ENDPOINTS.GET_POR_TIPO_CATEGORIAID_MAIS_SIGLA_ESTADO_USUARIO}`,
    API_URL_GET_POR_QUERY: `${API_BASE_URL_DEV}/${ENDPOINTS.GET_POR_QUERY}`
};

const PROD = {
    API_URL_GET_TODOS: `${API_BASE_URL_PROD}/${ENDPOINTS.GET_TODOS}`,
    API_URL_GET_POR_ID: `${API_BASE_URL_PROD}/${ENDPOINTS.GET_POR_ID}`,
    API_URL_POST_CRIAR: `${API_BASE_URL_PROD}/${ENDPOINTS.POST_CRIAR}`,
    API_URL_POST_ATUALIZAR: `${API_BASE_URL_PROD}/${ENDPOINTS.POST_ATUALIZAR}`,
    API_URL_POST_DELETAR: `${API_BASE_URL_PROD}/${ENDPOINTS.POST_DELETAR}`,
    API_URL_GET_POR_TIPO_CATEGORIAID_MAIS_SIGLA_ESTADO_USUARIO: `${API_BASE_URL_PROD}/${ENDPOINTS.GET_POR_TIPO_CATEGORIAID_MAIS_SIGLA_ESTADO_USUARIO}`,
    API_URL_GET_POR_QUERY: `${API_BASE_URL_PROD}/${ENDPOINTS.GET_POR_QUERY}`
};

// Definir se as constantes para a API é DEV ou PROD;
const CONSTANTS = process.env.NODE_ENV === 'development' ? DEV : PROD;

export default CONSTANTS;