const API_BASE_URL_DEV = 'https://localhost:7131/api';
const API_BASE_URL_PROD = 'https://fluxoapi.azurewebsites.net/api';

const ENDPOINTS = {
    GET_AUTENTICAR: 'UsuariosApi/autenticar',
    GET_VERIFICAR_EMAIL_E_SENHA: 'UsuariosApi/verificarEmailSenha',
    GET_IS_EXISTE_EMAIL: 'UsuariosApi/IsExistePorEmail',
    GET_IS_EXISTE_NOME_USUARIO: 'UsuariosApi/IsExistePorNomeUsuarioSistema',
    POST_CRIAR_CONTA: 'UsuariosApi/criar'
};

const DEV = {
    API_URL_GET_AUTENTICAR: `${API_BASE_URL_DEV}/${ENDPOINTS.GET_AUTENTICAR}`,
    API_URL_GET_VERIFICAR_EMAIL_E_SENHA: `${API_BASE_URL_DEV}/${ENDPOINTS.GET_VERIFICAR_EMAIL_E_SENHA}`,
    API_URL_GET_IS_EXISTE_EMAIL: `${API_BASE_URL_DEV}/${ENDPOINTS.GET_IS_EXISTE_EMAIL}`,
    API_URL_GET_IS_EXISTE_NOME_USUARIO: `${API_BASE_URL_DEV}/${ENDPOINTS.GET_IS_EXISTE_NOME_USUARIO}`,
    API_URL_POST_CRIAR: `${API_BASE_URL_DEV}/${ENDPOINTS.POST_CRIAR_CONTA}`
};

const PROD = {
    API_URL_GET_AUTENTICAR: `${API_BASE_URL_PROD}/${ENDPOINTS.GET_AUTENTICAR}`,
    API_URL_GET_VERIFICAR_EMAIL_E_SENHA: `${API_BASE_URL_PROD}/${ENDPOINTS.GET_VERIFICAR_EMAIL_E_SENHA}`,
    API_URL_GET_IS_EXISTE_EMAIL: `${API_BASE_URL_PROD}/${ENDPOINTS.GET_IS_EXISTE_EMAIL}`,
    API_URL_GET_IS_EXISTE_NOME_USUARIO: `${API_BASE_URL_PROD}/${ENDPOINTS.GET_IS_EXISTE_NOME_USUARIO}`,
    API_URL_POST_CRIAR: `${API_BASE_URL_PROD}/${ENDPOINTS.POST_CRIAR_CONTA}`
};

// Definir se as constantes para a API é DEV ou PROD;
const CONSTANTS = process.env.NODE_ENV === 'development' ? DEV : PROD;

export default CONSTANTS;