import { API_BASE_URL_DEV, API_BASE_URL_PROD } from '../../utilidades/utils/urlApi';

const ENDPOINTS = {
    GET_AUTENTICAR: 'UsuariosApi/autenticar',
    GET_VERIFICAR_EMAIL_E_SENHA: 'UsuariosApi/verificarEmailSenha',
    GET_IS_EXISTE_EMAIL: 'UsuariosApi/IsExistePorEmail',
    GET_IS_EXISTE_NOME_USUARIO: 'UsuariosApi/isExistePorNomeUsuarioSistema',
    POST_CRIAR_CONTA: 'UsuariosApi/criar',
    GET_POR_NOME_USUARIO_SISTEMA: 'UsuariosApi/getPorNomeUsuarioSistema',
    GET_POR_ID: 'UsuariosApi',
    POST_ATUALIZAR: 'UsuariosApi/atualizar',
    GET_CRIPTOGRAFAR: 'UsuariosApi/criptografarSenha',
    POST_UPAR_IMAGEM: 'UsuariosApi/uparArquivoReact',
    POST_ATUALIZAR_FOTO_PERFIL: 'UsuariosApi/atualizarFotoPerfil'
};

const DEV = {
    API_URL_GET_AUTENTICAR: `${API_BASE_URL_DEV}/${ENDPOINTS.GET_AUTENTICAR}`,
    API_URL_GET_VERIFICAR_EMAIL_E_SENHA: `${API_BASE_URL_DEV}/${ENDPOINTS.GET_VERIFICAR_EMAIL_E_SENHA}`,
    API_URL_GET_IS_EXISTE_EMAIL: `${API_BASE_URL_DEV}/${ENDPOINTS.GET_IS_EXISTE_EMAIL}`,
    API_URL_GET_IS_EXISTE_NOME_USUARIO: `${API_BASE_URL_DEV}/${ENDPOINTS.GET_IS_EXISTE_NOME_USUARIO}`,
    API_URL_POST_CRIAR: `${API_BASE_URL_DEV}/${ENDPOINTS.POST_CRIAR_CONTA}`,
    API_URL_GET_POR_NOME_USUARIO_SISTEMA: `${API_BASE_URL_DEV}/${ENDPOINTS.GET_POR_NOME_USUARIO_SISTEMA}`,
    API_URL_GET_POR_ID: `${API_BASE_URL_DEV}/${ENDPOINTS.GET_POR_ID}`,
    API_URL_POST_ATUALIZAR: `${API_BASE_URL_DEV}/${ENDPOINTS.POST_ATUALIZAR}`,
    API_URL_GET_CRIPTOGRAFAR: `${API_BASE_URL_DEV}/${ENDPOINTS.GET_CRIPTOGRAFAR}`,
    API_URL_POST_UPAR_IMAGEM: `${API_BASE_URL_DEV}/${ENDPOINTS.POST_UPAR_IMAGEM}`,
    API_URL_POST_ATUALIZAR_FOTO_PERFIL: `${API_BASE_URL_DEV}/${ENDPOINTS.POST_ATUALIZAR_FOTO_PERFIL}`
};

const PROD = {
    API_URL_GET_AUTENTICAR: `${API_BASE_URL_PROD}/${ENDPOINTS.GET_AUTENTICAR}`,
    API_URL_GET_VERIFICAR_EMAIL_E_SENHA: `${API_BASE_URL_PROD}/${ENDPOINTS.GET_VERIFICAR_EMAIL_E_SENHA}`,
    API_URL_GET_IS_EXISTE_EMAIL: `${API_BASE_URL_PROD}/${ENDPOINTS.GET_IS_EXISTE_EMAIL}`,
    API_URL_GET_IS_EXISTE_NOME_USUARIO: `${API_BASE_URL_PROD}/${ENDPOINTS.GET_IS_EXISTE_NOME_USUARIO}`,
    API_URL_POST_CRIAR: `${API_BASE_URL_PROD}/${ENDPOINTS.POST_CRIAR_CONTA}`,
    API_URL_GET_POR_NOME_USUARIO_SISTEMA: `${API_BASE_URL_PROD}/${ENDPOINTS.GET_POR_NOME_USUARIO_SISTEMA}`,
    API_URL_GET_POR_ID: `${API_BASE_URL_PROD}/${ENDPOINTS.GET_POR_ID}`,
    API_URL_POST_ATUALIZAR: `${API_BASE_URL_PROD}/${ENDPOINTS.POST_ATUALIZAR}`,
    API_URL_GET_CRIPTOGRAFAR: `${API_BASE_URL_PROD}/${ENDPOINTS.GET_CRIPTOGRAFAR}`,
    API_URL_POST_UPAR_IMAGEM: `${API_BASE_URL_PROD}/${ENDPOINTS.POST_UPAR_IMAGEM}`,
    API_URL_POST_ATUALIZAR_FOTO_PERFIL: `${API_BASE_URL_PROD}/${ENDPOINTS.POST_ATUALIZAR_FOTO_PERFIL}`
};

// Definir se as constantes para a API é DEV ou PROD;
const CONSTANTS = process.env.NODE_ENV === 'development' ? DEV : PROD;

export default CONSTANTS;