import { API_BASE_URL_DEV, API_BASE_URL_PROD } from '../../utilidades/utils/urlApi';

const ENDPOINTS = {
    GET_TODOS: 'EstabelecimentosApi/todos',
    GET_POR_ID: 'EstabelecimentosApi',
    POST_CRIAR: 'EstabelecimentosApi/criar',
    POST_ATUALIZAR: 'EstabelecimentosApi/atualizar',
    POST_DELETAR: 'EstabelecimentosApi/deletar',
    GET_POR_TIPO_ID_MAIS_SIGLA_ESTADO_USUARIO: 'EstabelecimentosApi/getPorEstabelecimentoTipoIdMaisCidadeIdUsuarioLogado',
    GET_POR_QUERY: 'EstabelecimentosApi/getPorQuery'
};

const DEV = {
    API_URL_GET_TODOS: `${API_BASE_URL_DEV}/${ENDPOINTS.GET_TODOS}`,
    API_URL_GET_POR_ID: `${API_BASE_URL_DEV}/${ENDPOINTS.GET_POR_ID}`,
    API_URL_POST_CRIAR: `${API_BASE_URL_DEV}/${ENDPOINTS.POST_CRIAR}`,
    API_URL_POST_ATUALIZAR: `${API_BASE_URL_DEV}/${ENDPOINTS.POST_ATUALIZAR}`,
    API_URL_POST_DELETAR: `${API_BASE_URL_DEV}/${ENDPOINTS.POST_DELETAR}`,
    API_URL_GET_POR_TIPO_ID_MAIS_SIGLA_ESTADO_USUARIO: `${API_BASE_URL_DEV}/${ENDPOINTS.GET_POR_TIPO_ID_MAIS_SIGLA_ESTADO_USUARIO}`,
    API_URL_GET_POR_QUERY: `${API_BASE_URL_DEV}/${ENDPOINTS.GET_POR_QUERY}`
};

const PROD = {
    API_URL_GET_TODOS: `${API_BASE_URL_PROD}/${ENDPOINTS.GET_TODOS}`,
    API_URL_GET_POR_ID: `${API_BASE_URL_PROD}/${ENDPOINTS.GET_POR_ID}`,
    API_URL_POST_CRIAR: `${API_BASE_URL_PROD}/${ENDPOINTS.POST_CRIAR}`,
    API_URL_POST_ATUALIZAR: `${API_BASE_URL_PROD}/${ENDPOINTS.POST_ATUALIZAR}`,
    API_URL_POST_DELETAR: `${API_BASE_URL_PROD}/${ENDPOINTS.POST_DELETAR}`,
    API_URL_GET_POR_TIPO_ID_MAIS_SIGLA_ESTADO_USUARIO: `${API_BASE_URL_PROD}/${ENDPOINTS.GET_POR_TIPO_ID_MAIS_SIGLA_ESTADO_USUARIO}`,
    API_URL_GET_POR_QUERY: `${API_BASE_URL_PROD}/${ENDPOINTS.GET_POR_QUERY}`
};

// Definir se as constantes para a API é DEV ou PROD;
const CONSTANTS = process.env.NODE_ENV === 'development' ? DEV : PROD;

export default CONSTANTS;